### ISSUE TITLE
0.1.1 Release Checklist

### ISSUE THREAD

**Issue by markjrieke** [markjrieke/workboots#31]
- [x] #3 check `{furrr}` mapping as option if installed
- [x] #6 add aliasing for other spellings
- [x] #7 add aliasing for other spellings
- [x] #29 update packages and checks for breaks
- [x] Update package version in DESCRIPTION
- [x] Update NEWS
- [x] modify current assertions for summarise_* functions
- [x] add new assertions as needed for new summarise_importance function
- [x] modify/add new test(s) as needed for assertions modification
- [x] add tests as needed for summarise_importance
- [x] review roxygen comments: all params described; all imports declared
- [x] run `devtools::document()`
- [x] run `devtools::check()`
- [x] probably update globals

**Comment by markjrieke** [comment]
assertions
- [ ] modify current assertions for summarise_* functions
- [ ] add new assertions as needed for new summarise_importance function

documentation
- [ ] review roxygen comments: all params described; all imports declared
- [ ] run `devtools::document()`
- [ ] run `devtools::check()`
- [ ] probably update globals

**Comment by markjrieke** [comment]
News updates:
* removed param summary_type in summarise_predictions 
* added new function: summarise_importance
* added aliasing for summarize_*

**Comment by markjrieke** [comment]
`furrr` doesn't actually improve speed. While this was expected for boosted models, which are more inherently serial, I was moderately surprised for other models. Some digging shows that pseudo environments are setup by parsnip underneath & this wouldn't be as simple of a fix as just adding `furrr::future_map_dfc()`. Not going to implement as a part of 0.1.1

**Comment by markjrieke** [comment]
closed by #35 and #36
