### ISSUE TITLE
0.2.0 checklist

### ISSUE THREAD

**Issue by markjrieke** [markjrieke/workboots#44]
## must haves
- [x] #14 
- [x] #15 
- [x] #40 
- [x] #43 
- [x] check all dependencies for minimum package version requirements
- [x] remove unnecessary fields from suggests
- [x] deprecate `conf` param in `summarise_*` functions (use `interval_width` instead)

## additional tasks from pkgdown
- [x] update plots in vignettes to be higher resolution
- [x] update getting started vignette
- [x] review all function documentation for clarity
- [x] update n in function documentation to 2000 to match deault
- [x] add a new vignette for a more-full walkthrough (tuning xgb model then predicting on boots)
- [x] update linear prediction interval vignette based on updates to params, function defaults, etc.

## nice-to-have
- [ ] #10 
- [ ] #32 
- [ ] #33 
- [ ] #39 
- [ ] #42
- [ ] #45

**Comment by markjrieke** [comment]
TL to complete by 6/14
